* The Nelson Goodman Principle

Suppose someone is standing at the fork of a road; one road leads to the town of Pleasantville, which you ish to visit, and the other road doesn't. The indivisual knows which road leads to Pleasantville, but he either always lies or alwayas tells the truth. What question would you ask him to find out which is the correct road to Pleasantville?

** Answer

"Are you able to say that this road leads to Pleasantville?". Adding "are you able to" to the beginning of a question adds a second layer to the question. A liar lies in both layers, which cancel each other out.

* The Absentminded Logician I

The logician is married to either Teresa, who always tells the truth, or Leonore, who always lies. He doesn't know which. The other isn't married. He meets one of them: what three word yes/no question can he ask to determine if she's his wife?

** Answer

"Is Teresa married."

Yes -> his wife
No -> not his wife.

Consider "are you married?"

Why not look at the ring?

* The Absentminded Logician II

What if he meets one of them, and wants to find out if his wife's name is Teresa or Leonore? Reminder: Teresa tells the Truth, and Leonore always Lies.

** Answer

"Are you married."

Yes -> Teresa is his wife
No -> Leonore is his wife

* The Absentminded Logician III

Suppose the logician wants to find out both the identity of the lady he meets /and/ the first name of his wife. He can only ask a yes/no question, but there is no restriction on the number of words in the question.

Can you find a question that will work?

** Answer

No such question exists! There are 4 possibilities (talking to either sister, married to either sister), and there are only 2 possible answers to a yes/no question.
